name: Gautamtalks
favicon: null
layout_spectrum: 0.19807186536490917
typography_spectrum: 0.024089240934699774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1874948034528643
  lightness: 0.3565094836521894
  saturation: 0.8610269799828529
  rhythmicContrast: 0.34185566334053874
purpose: []
