name: Econtalk
favicon: null
layout_spectrum: 0.60821
typography_spectrum: 1
title: 'On Economics, By Gautam.'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#2B4D69'
    - '#94999F'
    - '#B3B7C0'
    - '#EBEBEE'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
