name: Gautamtalks
favicon: null
layout_spectrum: 0.76234
typography_spectrum: 1
title: 'On Economics, By Gautam.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272b34'
    - '#ffffff'
    - '#d6dadc'
    - '#5c5c5e'
    - '#949899'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
